spring.application.name=ecommerceusb
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_usb_db
spring.datasource.username=john
spring.datasource.password=clubten121
spring.datasource.driver-class-name=org.postgresql.Driver
